---
refresh_interval: 2 # seconds
max_price: 750 # dollars
urls:
  - https://www.amazon.com/PlayStation-5-Console/dp/B08FC5L3RG
  - https://www.carrefour.fr/p/console-playstation-5-edition-standard-sony-interactive-0711719395201
