var loadbeeVersion="v2020-03-31-button";"object"!==typeof JSON&&(JSON={});
(function(){function A(d){return 10>d?"0"+d:d}function q(d){u.lastIndex=0;return u.test(d)?'"'+d.replace(u,function(f){var g=h[f];return"string"===typeof g?g:"\\u"+("0000"+f.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+d+'"'}function y(d,f){var g=l,e=f[d];e&&"object"===typeof e&&"function"===typeof e.toJSON&&(e=e.toJSON(d));"function"===typeof k&&(e=k.call(f,d,e));switch(typeof e){case "string":return q(e);case "number":return isFinite(e)?String(e):"null";case "boolean":case "null":return String(e);
case "object":if(!e)return"null";l+=t;var r=[];if("[object Array]"===Object.prototype.toString.apply(e)){var w=e.length;for(d=0;d<w;d+=1)r[d]=y(d,e)||"null";f=0===r.length?"[]":l?"[\n"+l+r.join(",\n"+l)+"\n"+g+"]":"["+r.join(",")+"]";l=g;return f}if(k&&"object"===typeof k)for(w=k.length,d=0;d<w;d+=1){if("string"===typeof k[d]){var p=k[d];(f=y(p,e))&&r.push(q(p)+(l?": ":":")+f)}}else for(p in e)Object.prototype.hasOwnProperty.call(e,p)&&(f=y(p,e))&&r.push(q(p)+(l?": ":":")+f);f=0===r.length?"{}":l?
"{\n"+l+r.join(",\n"+l)+"\n"+g+"}":"{"+r.join(",")+"}";l=g;return f}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+A(this.getUTCMonth()+1)+"-"+A(this.getUTCDate())+"T"+A(this.getUTCHours())+":"+A(this.getUTCMinutes())+":"+A(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var l,t,k;if("function"!==typeof JSON.stringify){var u=
/[\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;var h={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};JSON.stringify=function(d,f,g){var e;t=l="";if("number"===typeof g)for(e=0;e<g;e+=1)t+=" ";else"string"===typeof g&&(t=g);if((k=f)&&"function"!==typeof f&&("object"!==typeof f||"number"!==typeof f.length))throw Error("JSON.stringify");return y("",{"":d})}}if("function"!==typeof JSON.parse){var v=
/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;JSON.parse=function(d,f){function g(e,r){var w,p=e[r];if(p&&"object"===typeof p)for(w in p)if(Object.prototype.hasOwnProperty.call(p,w)){var B=g(p,w);void 0!==B?p[w]=B:delete p[w]}return f.call(e,r,p)}d=String(d);v.lastIndex=0;v.test(d)&&(d=d.replace(v,function(e){return"\\u"+("0000"+e.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(d.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+d+")"),"function"===typeof f?g({"":d},""):d;throw new SyntaxError("JSON.parse");}}})();
var loadbeeJSONP=function(){function A(k,u){var h=document.createElement("script"),v=!1;h.src=k;h.async=!0;var d=u||t.error;"function"===typeof d&&(h.onerror=function(f){d({url:k,event:f})});h.onload=h.onreadystatechange=function(){v||this.readyState&&"loaded"!==this.readyState&&"complete"!==this.readyState||(v=!0,h.onload=h.onreadystatechange=null,h&&h.parentNode&&h.parentNode.removeChild(h))};y||(y=document.getElementsByTagName("head")[0]);y.appendChild(h)}var q=0,y,l=this,t={};return{get:function(k,
u,h,v){var d=-1===(k||"").indexOf("?")?"?":"&",f;v=v||t.callbackName||"callback";var g=v+"_json"+ ++q;u=u||{};for(f in u)u.hasOwnProperty(f)&&(d+=encodeURIComponent(f)+"="+encodeURIComponent(u[f])+"&");l[g]=function(e){h(e);try{delete l[g]}catch(r){}l[g]=null};A(k+d+v+"="+g);return g},init:function(k){t=k}}}(),loadbeeService=function(){var A="",q="",y=!1,l=!1,t=!1,k=!1,u=!1,h=!1,v=!1,d=!1,f=null,g=!1,e=function(a){var b={manufacturer:"",product:"",presenter:""};b.language=A;b.buttonLanguage="en";
b.button="default";b.css="default";b.template="default";void 0!==loadbeeProductCode&&(b.product=loadbeeProductCode);void 0!==loadbeeManufacturer&&(b.manufacturer=loadbeeManufacturer);void 0!==loadbeeLanguage&&(b.language=loadbeeLanguage,b.buttonLanguage=b.language);a.hasAttribute("data-loadbee-language")&&(b.language=a.getAttribute("data-loadbee-language"),b.buttonLanguage=b.language);a.hasAttribute("data-loadbee-buttonLanguage")&&"default"!==a.getAttribute("data-loadbee-buttonLanguage")&&(b.buttonLanguage=
b.language);a.hasAttribute("data-loadbee-button")&&(b.button=a.getAttribute("data-loadbee-button"));a.hasAttribute("data-loadbee-css")&&(b.css=a.getAttribute("data-loadbee-css"));a.hasAttribute("data-loadbee-template")&&(b.template=a.getAttribute("data-loadbee-template"));a.hasAttribute("data-loadbee-manufacturer")&&(b.manufacturer=a.getAttribute("data-loadbee-manufacturer"));a.hasAttribute("data-loadbee-product")&&(b.product=a.getAttribute("data-loadbee-product"));a.hasAttribute("data-loadbee-showInNewWindow")&&
1==a.getAttribute("data-loadbee-showInNewWindow")&&(g=a.getAttribute("data-loadbee-showInNewWindow"));a.setAttribute("data-loadbee-language",b.language);a.setAttribute("data-loadbee-button",b.button);a.setAttribute("data-loadbee-css",b.css);a.setAttribute("data-loadbee-template",b.template);a.setAttribute("data-loadbee-buttonlanguage",b.buttonLanguage);return b},r=function(){return null!==f?f:f=(new Date).getTime()},w=function(a,b,c,m){var z=loadbeeReferrer?{apiKey:q,groupbytime:r(),__integration:loadbeeVersion,
template:a.template,referrer:loadbeeReferrer}:{apiKey:q,groupbytime:r(),__integration:loadbeeVersion,template:a.template};loadbeeJSONP.get(b,z,function(n){a:{for(x in n)if(n.hasOwnProperty(x)){var x=!1;break a}x=JSON.stringify(n)===JSON.stringify({})}x?"undefined"!==typeof loadbeeProductNotFoundCallback&&loadbeeProductNotFoundCallback():(n.css=a.css,n.template=a.template,n.button=a.button,n.buttonLanguage=a.buttonLanguage,void 0!==a.presenter&&(n.presenter=a.presenter),"undefined"!==typeof loadbeeProductFoundCallback&&
loadbeeProductFoundCallback(),m(n,c))})},p=function(){var a=setInterval(function(){var b=document.getElementById("loadbeeTabContent");"undefined"!==typeof b&&""!==b&&null!=b&&"undefined"!==typeof b.iFrameResizer&&""!==b.iFrameResizer&&null!=b.iFrameResizer&&(null!=b.offsetParent&&clearInterval(a),b.iFrameResizer.resize())},500)},B=function(){v||(d?C("https://d25jbgvg9kmxad.cloudfront.net/css/loadbee.ie.css"):C("https://d25jbgvg9kmxad.cloudfront.net/css/loadbee.css"),k&&!t&&C("https://d25jbgvg9kmxad.cloudfront.net/css/loadbeeTablet.css"),
t&&C("https://d25jbgvg9kmxad.cloudfront.net/css/loadbeeMobile.css"),v=!0)},F=function(a){y||(C("https://button.loadbee.com/css/"+a.manufacturer+"/"+q+"/button.css"),y=!0)},J=function(a,b){var c="",m=a.text["default"];void 0!==a.text[a.button]&&(m=a.text[a.button]);c=void 0!==a.image?"right"===a.text.align?c+(a.image+m):c+(m+a.image):m;B();F(a);-1< !(" "+b.className+" ").indexOf(" loadbeeShowActiveLink ")&&(b.className+=" loadbeeShowActiveLink");b.innerHTML=c;b.addEventListener("click",function(z){z.preventDefault();
a.extra={shop:D(),source:"link",api:q};null!==b.getAttribute("data-extra")&&(a.extra.type=b.getAttribute("data-extra"));null!==b.getAttribute("data-loadbee-disablemodalbackbutton")&&(h=b.getAttribute("data-loadbee-disablemodalbackbutton"));z="string"==typeof a.endpoint?"https://"+a.endpoint+".loadbee.com":"https://service.loadbee.com";var n="/ean/"+encodeURIComponent(a.ident)+"/"+a.language+"?css="+a.css+"&template="+a.template+"&button="+a.button;n+="&data="+encodeURIComponent(JSON.stringify(a.extra));
G(z,n)})},K=function(a,b){a.extra={shop:D(),source:"inpage",api:q};null!==b.getAttribute("data-extra")&&(a.extra.type=b.getAttribute("data-extra"));var c="string"==typeof a.endpoint?"https://"+a.endpoint+".loadbee.com":"https://service.loadbee.com",m="/ean/"+encodeURIComponent(a.ident)+"/"+a.language+"?css="+a.css+"&template="+a.template+"&button="+a.button;m+="&data="+encodeURIComponent(JSON.stringify(a.extra));-1< !(" "+b.className+" ").indexOf(" loadbeeShowActiveTab ")&&(b.className+=" loadbeeShowActiveTab");
a=document.getElementsByClassName("loadbeeTabContent");a[0]&&(a[0].innerHTML='<iframe id="loadbeeTabContent" allowfullscreen="allowfullscreen" width="100%" scrolling="no" frameborder="0" src="'+c+m+'"></iframe>',H("https://cdn.loadbee.com/js/iframeResizer.min.js",function(){iFrameResize({log:!1,checkOrigin:!1,onResized:function(z){"undefined"!==typeof loadbeeResizeCallback&&loadbeeResizeCallback(z)}})}))},D=function(){if(loadbeeReferrer){var a=document.createElement("a");a.href=loadbeeReferrer;return a.hostname}return window.location.hostname},
L=function(a,b){usePostMessage&&parent.postMessage("exists/"+encodeURIComponent(a.manufacturer)+"/"+encodeURIComponent(a.code)+"/"+a.language,loadbeeParentUrl);B();F(a);-1< !(" "+b.className+" ").indexOf(" loadbeeButton"+a.button+" ")&&(b.className+=" loadbeeButton"+a.button);-1< !(" "+b.className+" ").indexOf(" loadbeeShowActiveButton ")&&(b.className+=" loadbeeShowActiveButton");-1< !(" "+b.className+" ").indexOf(" loadbeeActiveButton ")&&(b.className+=" loadbeeActiveButton");-1< !(" "+b.className+
" ").indexOf(" loadbeeButtonLanguage-"+a.buttonLanguage+" ")&&(b.className+=" loadbeeButtonLanguage-"+a.buttonLanguage);b.addEventListener("click",function(c){c.preventDefault();a.extra={shop:D(),source:"button",api:q};null!==b.getAttribute("data-extra")&&(a.extra.type=b.getAttribute("data-extra"));null!==b.getAttribute("data-loadbee-disablemodalbackbutton")&&(h=b.getAttribute("data-loadbee-disablemodalbackbutton"));c="string"==typeof a.endpoint?"https://"+a.endpoint+".loadbee.com":"https://service.loadbee.com";
var m="/ean/"+encodeURIComponent(a.ident)+"/"+a.language+"?css="+a.css+"&template="+a.template+"&button="+a.button;m+="&data="+encodeURIComponent(JSON.stringify(a.extra));G(c,m)})},I={},G=function(a,b){if(usePostMessage)parent.postMessage(a+b,loadbeeParentUrl);else if(!0===g)window.open(a+b);else{var c=document.createElement("div");c.id="loadbee-overlay";c.style.display="none";var m=document.createElement("div");m.id="loadbee-wrapper";m.style.display="none";var z=document.createElement("div");z.id=
"loadbee-close";var n=document.createElement("iframe");n.id="loadbee-popup";n.frameBorder="0";n.allowfullscreen="allowfullscreen";m.appendChild(z);m.appendChild(n);c.appendChild(m);document.getElementsByTagName("body")[0].appendChild(c);u&&(!1===l?H("https://d25jbgvg9kmxad.cloudfront.net/js/iframeResizer.min.js",function(){iFrameResize({log:!1,checkOrigin:!1});l=!0}):iFrameResize({log:!1,checkOrigin:!1}));c.addEventListener("click",function(x){x.stopPropagation();E()});z.addEventListener("click",
function(x){x.stopPropagation();E()});n.src=a+b;c.style.display="block";m.style.display="block";(t||k)&&!0!==h&&(a=function(x){x=x.oldURL.split("#");x[1]&&"lbpopup"===x[1].split("-")[0]&&E()},b=window.location.hash.split("-"),void 0===b[0]||"lbpopup"!==b[0]&&"#lbpopup"!==b[0]||(void 0===b[1]||""===b[1]?history.pushState("",document.title,window.location.pathname+window.location.search):(b.shift(),history.pushState({},"",""+b.join("-")))),history.pushState({},"","#lbpopup-"+window.location.hash),window.addEventListener("hashchange",
a),I.mobileHashChange=a)}},E=function(){var a=document.getElementById("loadbee-popup");null!==a&&(a.src="",a.parentNode.removeChild(a));a=document.getElementById("loadbee-overlay");null!==a&&(a.style.display="none",a.parentNode.removeChild(a));a=document.getElementById("loadbee-close");null!==a&&(a.style.display="none",a.parentNode.removeChild(a));a=document.getElementById("loadbee-wrapper");null!==a&&(a.style.display="none",a.parentNode.removeChild(a));(t||k)&&!0!==h&&(window.removeEventListener("hashchange",
I.mobileHashChange),a=window.location.hash.split("-"),void 0===a[0]||"lbpopup"!==a[0]&&"#lbpopup"!==a[0]||(void 0===a[1]||""===a[1]?history.pushState("",document.title,window.location.pathname+window.location.search):(a.shift(),history.pushState({},"",""+a.join("-")))))},C=function(a){var b=document.createElement("link");b.setAttribute("rel","stylesheet");b.setAttribute("type","text/css");b.setAttribute("media","screen");b.setAttribute("charset","utf-8");b.setAttribute("href",a);document.getElementsByTagName("head")[0].appendChild(b)},
H=function(a,b){var c=document.createElement("script");c.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(c,a);c.onload=b;a.appendChild(c)};return{requestAll:function(){A=navigator.language||navigator.userLanguage;t=null!==navigator.userAgent.match(/(iPhone|iPod|iPad|BlackBerry|Android|IEMobile)/)&&600>screen.width;k=null!==navigator.userAgent.match(/(iPhone|iPod|iPad|BlackBerry|Android|IEMobile)/);navigator.userAgent.match(/(iPad)/);u=null!==navigator.userAgent.match(/(iPhone|iPod|iPad)/);
var a=navigator.userAgent,b=/(msie|trident)/i.test(a);q="Hgc3GdEyHDu2HEtzCcA24rPG2D9kebwM";void 0!==loadbeeApiKey&&(q=loadbeeApiKey);("XF8k2DEJUERJRVxPxyRp5e7nGtRNyH2c"==q||"Bp75U3D2vcrEbbhCxp3htHa5cyN2Jr39"==q)&&t&&(g=!0);b&&(a=parseInt(a.match(/(msie |rv:)(\d+(\.\d+)?)/i)[2]),9>document.documentMode||a!==document.documentMode)&&(d=!0);a=document.getElementsByClassName("loadbeeLink");for(b=0;b<a.length;b++)if("object"===typeof a[b]&&-1< !(" "+a[b].className+" ").indexOf(" loadbeeShowActiveLink ")){var c=
e(a[b]);""!==c.manufacturer&&""!==c.product&&""!==c.language&&w(c,"https://button.loadbee.com/"+encodeURIComponent(c.manufacturer)+"/"+encodeURIComponent(c.product)+"/"+c.language,a[b],J)}a=document.getElementsByClassName("loadbeeButton");for(b=0;b<a.length;b++)"object"===typeof a[b]&&-1< !(" "+a[b].className+" ").indexOf(" loadbeeShowActiveButton ")&&(c=e(a[b]),""!==c.manufacturer&&""!==c.product&&""!==c.language&&w(c,"https://button.loadbee.com/"+encodeURIComponent(c.manufacturer)+"/"+encodeURIComponent(c.product)+
"/"+c.language,a[b],L));a=document.getElementsByClassName("loadbeeTab");for(b=0;b<a.length;b++)"object"===typeof a[b]&&-1< !(" "+a[b].className+" ").indexOf(" loadbeeShowActiveTab ")&&(c=e(a[b]),""!==c.manufacturer&&""!==c.product&&""!==c.language&&w(c,"https://button.loadbee.com/"+encodeURIComponent(c.manufacturer)+"/"+encodeURIComponent(c.product)+"/"+c.language,a[b],K));p()}}}();if(void 0===loadbeeJsLoaded)var loadbeeJsLoaded=!1;if(void 0===loadbeeApiKey)var loadbeeApiKey="Hgc3GdEyHDu2HEtzCcA24rPG2D9kebwM";
if(void 0===loadbeeProductCode)var loadbeeProductCode="";if(void 0===loadbeeManufacturer)var loadbeeManufacturer="";if(void 0===loadbeeLanguage)var loadbeeLanguage="";if(void 0===loadbeeReferrer)var loadbeeReferrer=!1;if(void 0===usePostMessage)var usePostMessage=!1;loadbeeService.requestAll();
